### ISSUE TITLE
Error Regarding Module Type and .js File

### ISSUE THREAD

**Issue by bdhack23** [comp426-2022-fall/a04#2]
<img width="644" alt="express_module" src="https://user-images.githubusercontent.com/77807845/200458114-1fb54c69-0747-455c-91e8-eb3df52a3663.PNG">

In my autograder results, a bunch of tests are failing because of this same issue. I changed my "type" to module and even put "type" right under "name" in package.json. But it doesn't seem to like the type "module" and having .js files apparently? What do I do? This is the second assignment that is giving me issues regarding my npm package "type" field, and I'm getting concerned.

**Comment by jdmar3** [comment]
Have you tried removing the `"type": "module",` line entirely from the `package.json` file.

If you are using `require()`, which is a CommonJS method, then it will remain incompatible with ES methods, which is what `"type": "module",` specifies, for this purpose, using `import` rather than require. 

There are several solutions here:

1. Remove `"type": "module"` from `package.json` and see what happens. It defaults to CommonJS if there is no type specified. https://nodejs.org/api/packages.html#type
2. Change `const http = require('express');` to `import {express} from 'express';` and then have `const app = express();` on the next line. (The const should be `app` rather than `http` if you want to be able to follow and make sense of examples. But fundamentally it doesn't matter as long as you are consistent in your usage throughout your script and understand what that const means.) https://www.robinwieruch.de/node-js-express-tutorial/
3. Create a hybrid state in which you import `require` from the core Node.js builtins and then you can use both `require` and import and it won't care. You can do that by adding, at the very top of your main file, the following: 
```
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
```
https://nodejs.org/docs/latest-v16.x/api/module.html#modulecreaterequirefilename

**Comment by bdhack23** [comment]
I tried all three of those solutions and none helped. :(
