### ISSUE TITLE
Cannot Get Correct Results

### ISSUE THREAD

**Issue by bdhack23** [comp426-2022-fall/a04#4]
I cannot seem to figure out what is wrong with my code. I can never seem to get my sides/dice/rolls/results to match the expected outcome. These are the autograder results:
<img width="631" alt="results_zero" src="https://user-images.githubusercontent.com/77807845/202307539-6640bbf5-3ef8-44b0-8615-56d77311a56a.PNG">
<img width="634" alt="results_zero_secondpic" src="https://user-images.githubusercontent.com/77807845/202307552-f1c75cbe-1576-45f1-a3d2-0eee364d338d.PNG">

This is my lib.roll file, in case my roll function logic is wrong:
<img width="399" alt="lib_roll_pic" src="https://user-images.githubusercontent.com/77807845/202307572-09b60087-d7df-4f31-ab60-7647d61e789e.PNG">

I was hoping for any insight into what I am doing incorrectly because I am stumped. Thanks in advance!

**Comment by yuualice** [comment]
Hi Brooke! 

You have the correct logic for generating the random rolls on your line 5.
One piece of logic you are missing here is that you are not accounting for the number of dice, as you are only looping through your # of rolls. Multiple dice thrown at once should be considered as one roll, and we would want to sum up those individual random values. For example, if we throw 3 6-sided dice once, the number we could get as a result would be [3-18], not [1-6,1-6,1-6].  Since we have two dice in this scenario, we would want to get a sum of random numbers from two dice in your result array. 

Hope this explanation helped :)
